name: Binance Signal Bot

on:
  schedule:
    - cron: "*/5 * * * *"  # jalan tiap 5 menit
  workflow_dispatch:        # bisa dijalankan manual juga

jobs:
  run-bot:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      SYMBOLS: "BTCUSDT,ETHUSDT"
      TIMEFRAMES: "1m,5m,15m"
      POLL_INTERVAL: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run trading signal bot
        run: |
          python bot.py
