name: Run Signal Scanner

on:
  schedule:
    - cron: '*/15 * * * *'   # setiap 15 menit (UTC)
  workflow_dispatch:          # juga bisa dijalankan manual

jobs:
  scan:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        run: python bot.py
